In [2]:
import numpy as np
NumP_Array = np.array([[1,2,3], [2,6,7]])

In [3]:
NP1 = np.array([[1,3], [4,5]])

NP2 = np.array([[3,4], [5,7]])

MNP = NP1@NP2
print(MNP)
#@ = multiplica utilizando as regras das matrizes

[[18 25]
 [37 51]]


In [4]:
#Multiplicação de elemento por elemento
MNP = NP1*NP2
MNP

array([[ 3, 12],
       [20, 35]])

In [5]:
#=@
MNP3 = np.dot(NP1, NP2)
MNP3

array([[18, 25],
       [37, 51]])

In [6]:
Sm1 = NP1+NP2
Sm1

array([[ 4,  7],
       [ 9, 12]])

In [7]:
Sub1=NP1-NP2
Sub1

array([[-2, -1],
       [-1, -2]])

In [ ]:
Sub2 = np.subtract(NP1,NP2)

In [9]:
Data_N = np.array([1, 3, 4, 5, 7, 9])
Data_N

array([1, 3, 4, 5, 7, 9])

In [11]:
#Média
Mean_N = np.mean(Data_N)
Mean_N

4.833333333333333

In [12]:
#Mediana
Median_N = np.median(Data_N)
Median_N

4.5

In [14]:
#Variancia

var_N = np.var(Data_N)

var_N

6.805555555555556

In [16]:
#Desvio padrão

SD_N = np.std(Data_N)
SD_N

2.608745973749755

In [17]:
NumP_Array = np.array([[1,2,3], [4,6,7]])

In [18]:
#
var_nump = np.var(NumP_Array, axis=1)
var_nump
#Retorna a vaciancia de cada uma das filas

array([0.66666667, 1.55555556])

In [19]:
var_nump2 = np.var(NumP_Array, axis=0)
var_nump2
#Retorna uma variância para cada coluna

array([2.25, 4.  , 4.  ])